package edu.uiu.aoop.careerforge.web;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import edu.uiu.aoop.careerforge.domain.Role;
import edu.uiu.aoop.careerforge.event.CareerMilestoneEvent;
import edu.uiu.aoop.careerforge.security.AppPrincipal;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/**
 * Persistent, progressively difficult assessments.  The question generator is
 * deterministic and explainable so the core learning flow remains available
 * without a third-party model; the Python AI service can later replace it.
 */
@RestController
@RequestMapping("/adaptive-assessment")
public class AdaptiveAssessmentController {
  private static final int QUESTIONS = 6, PASSING = 4, MINUTES = 12;
  private final JdbcTemplate jdbc; private final ObjectMapper json; private final ApplicationEventPublisher events;
  public AdaptiveAssessmentController(JdbcTemplate jdbc, ObjectMapper json, ApplicationEventPublisher events) { this.jdbc=jdbc; this.json=json; this.events=events; }
  private void student(AppPrincipal p) { if(p.role()!=Role.student) throw new ApiException(HttpStatus.FORBIDDEN,"Student account required"); }

  @GetMapping("/overview")
  Map<String,Object> overview(@AuthenticationPrincipal AppPrincipal p) { student(p); Map<String,Object> profile=profile(p.id()); List<String> missing=missing(profile); Map<String,Object> program=program(p.id()); return Map.of("aiConfigured",true,"profileReady",missing.isEmpty(),"missingFields",missing,"passingQuestionCount",PASSING,"questionsPerLevel",QUESTIONS,"timeLimitMinutes",MINUTES,"program",programPayload(program),"activeAttempt",activeAttempt(p.id())); }

  @PostMapping("/start") @Transactional
  Map<String,Object> start(@AuthenticationPrincipal AppPrincipal p) { student(p); Map<String,Object> profile=profile(p.id()); List<String> missing=missing(profile); if(!missing.isEmpty()) throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Complete your Personal & career details first: "+String.join(", ",missing)); Map<String,Object> running=activeAttempt(p.id()); if(running!=null) return Map.of("resumed",true,"attempt",running); Map<String,Object> program=program(p.id()); if(program==null) { jdbc.update("INSERT INTO adaptive_assessment_programs (user_id) VALUES (?)",p.id()); program=program(p.id()); } if("completed".equals(program.get("status"))) throw new ApiException(HttpStatus.CONFLICT,"You have already completed all 10 levels"); int level=Math.max(1,Math.min(10,number(program.get("current_level"),1))); String id=UUID.randomUUID().toString(); Instant expiry=Instant.now().plus(MINUTES,ChronoUnit.MINUTES); List<Map<String,Object>> questions=questions(profile,level); jdbc.update("INSERT INTO adaptive_assessment_attempts (id,user_id,level_number,difficulty_label,profile_snapshot,questions_json,generated_model,expires_at) VALUES (?,?,?,?,CAST(? AS JSON),CAST(? AS JSON),?,?)",id,p.id(),level,difficulty(level),write(Map.of("targetRole",text(profile.get("target_role")),"degree",text(profile.get("degree")))),write(questions),"careerforge-rule-based",expiry); return Map.of("resumed",false,"attempt",Objects.requireNonNull(activeAttempt(p.id()))); }

  @PostMapping("/attempts/{id}/submit") @Transactional
  Map<String,Object> submit(@AuthenticationPrincipal AppPrincipal p,@PathVariable String id,@RequestBody Map<String,Object> body) { student(p); Map<String,Object> attempt=jdbc.query("SELECT id,level_number,questions_json,status,expires_at FROM adaptive_assessment_attempts WHERE id=? AND user_id=?",rs->{if(!rs.next())return null;Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getString("id"));row.put("level_number",rs.getInt("level_number"));row.put("questions_json",rs.getString("questions_json"));row.put("status",rs.getString("status"));row.put("expires_at",rs.getTimestamp("expires_at").toInstant());return row;},id,p.id()); if(attempt==null) throw new ApiException(HttpStatus.NOT_FOUND,"Assessment attempt not found"); if(!"started".equals(attempt.get("status"))) throw new ApiException(HttpStatus.CONFLICT,"This assessment was already submitted"); if(((Instant)attempt.get("expires_at")).isBefore(Instant.now())) { jdbc.update("UPDATE adaptive_assessment_attempts SET status='expired' WHERE id=?",id); throw new ApiException(HttpStatus.GONE,"This assessment attempt has expired"); }
    List<Map<String,Object>> questions=readList((String)attempt.get("questions_json")); Map<String,Integer> answers=new HashMap<>(); if(body.get("answers") instanceof List<?> values) for(Object value:values) if(value instanceof Map<?,?> answer) answers.put(String.valueOf(answer.get("questionId")),number(answer.get("optionIndex"),-1)); int correct=0; List<Map<String,Object>> review=new ArrayList<>(); for(Map<String,Object> question:questions){int expected=number(question.get("correctIndex"),-1); int selected=answers.getOrDefault(String.valueOf(question.get("id")),-1); boolean right=expected==selected; if(right) correct++; review.add(Map.of("id",question.get("id"),"focusArea",question.get("focusArea"),"prompt",question.get("prompt"),"options",question.get("options"),"correctIndex",expected,"correct",right,"explanation",question.get("explanation"))); } int percentage=(int)Math.round(correct*100d/QUESTIONS); boolean passed=correct>=PASSING; int level=number(attempt.get("level_number"),1); jdbc.update("UPDATE adaptive_assessment_attempts SET answers_json=CAST(? AS JSON),status='completed',correct_count=?,percentage=?,passed=?,completed_at=NOW() WHERE id=?",write(body.getOrDefault("answers",List.of())),correct,percentage,passed,id); jdbc.update("INSERT INTO adaptive_assessment_programs (user_id,current_level,highest_level_completed,total_questions,total_correct,status,completed_at) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE current_level=VALUES(current_level),highest_level_completed=GREATEST(highest_level_completed,VALUES(highest_level_completed)),total_questions=total_questions+VALUES(total_questions),total_correct=total_correct+VALUES(total_correct),status=VALUES(status),completed_at=VALUES(completed_at)",p.id(),passed?Math.min(10,level+1):level,passed?level:Math.max(0,level-1),QUESTIONS,correct,passed&&level==10?"completed":"active",passed&&level==10?java.sql.Timestamp.from(Instant.now()):null); events.publishEvent(new CareerMilestoneEvent(p.id(),CareerMilestoneEvent.Type.ASSESSMENT_COMPLETED)); Map<String,Object> result=new LinkedHashMap<>();result.put("level",level);result.put("correctCount",correct);result.put("questionCount",QUESTIONS);result.put("percentage",percentage);result.put("passed",passed);result.put("nextLevel",passed&&level<10?level+1:null);result.put("review",review);return Map.of("result",result,"program",programPayload(program(p.id()))); }

  private Map<String,Object> profile(Long userId) { return jdbc.query("SELECT university,degree,graduation_year,target_role,location,career_interests FROM student_profiles WHERE user_id=?",rs->{if(!rs.next())return Map.of();Map<String,Object> profile=new LinkedHashMap<>();for(String key:List.of("university","degree","graduation_year","target_role","location","career_interests"))profile.put(key,rs.getObject(key));return profile;},userId); }
  private List<String> missing(Map<String,Object> profile) { List<String> fields=new ArrayList<>(); if(text(profile.get("university")).isBlank())fields.add("university");if(text(profile.get("degree")).isBlank())fields.add("degree");if(text(profile.get("graduation_year")).isBlank())fields.add("graduation year");if(text(profile.get("target_role")).isBlank())fields.add("target role");if(text(profile.get("location")).isBlank())fields.add("location");if(readStrings(text(profile.get("career_interests"))).isEmpty())fields.add("career interests");return fields; }
  private Map<String,Object> program(Long userId) { return jdbc.query("SELECT current_level,highest_level_completed,total_questions,total_correct,status FROM adaptive_assessment_programs WHERE user_id=?",rs->{if(!rs.next())return null;Map<String,Object> value=new LinkedHashMap<>();for(String key:List.of("current_level","highest_level_completed","total_questions","total_correct","status"))value.put(key,rs.getObject(key));return value;},userId); }
  private Map<String,Object> programPayload(Map<String,Object> program) { int current=Math.max(1,Math.min(10,number(program==null?null:program.get("current_level"),1)));int complete=Math.max(0,Math.min(10,number(program==null?null:program.get("highest_level_completed"),0)));List<Map<String,Object>> levels=new ArrayList<>();for(int level=1;level<=10;level++){String state=complete>=level?"completed":current==level&&!"completed".equals(program==null?null:program.get("status"))?"unlocked":"locked";levels.add(Map.of("level",level,"label",label(level),"difficulty",difficulty(level),"state",state));}return Map.of("currentLevel",current,"highestLevelCompleted",complete,"totalQuestions",number(program==null?null:program.get("total_questions"),0),"totalCorrect",number(program==null?null:program.get("total_correct"),0),"status",program==null?"active":program.get("status"),"levels",levels); }
  private Map<String,Object> activeAttempt(Long userId) { jdbc.update("UPDATE adaptive_assessment_attempts SET status='expired' WHERE user_id=? AND status='started' AND expires_at<=NOW()",userId);return jdbc.query("SELECT id,level_number,difficulty_label,questions_json,started_at,expires_at FROM adaptive_assessment_attempts WHERE user_id=? AND status='started' AND expires_at>NOW() ORDER BY started_at DESC LIMIT 1",rs->{if(!rs.next())return null;List<Map<String,Object>> visible=new ArrayList<>();for(Map<String,Object> item:readList(rs.getString("questions_json"))){Map<String,Object> copy=new LinkedHashMap<>(item);copy.remove("correctIndex");copy.remove("explanation");visible.add(copy);}return Map.of("id",rs.getString("id"),"level",rs.getInt("level_number"),"difficulty",rs.getString("difficulty_label"),"questions",visible,"questionCount",QUESTIONS,"passingQuestionCount",PASSING,"startedAt",rs.getTimestamp("started_at").toInstant(),"expiresAt",rs.getTimestamp("expires_at").toInstant());},userId); }
  private List<Map<String,Object>> questions(Map<String,Object> profile,int level) { String role=text(profile.get("target_role"));String degree=text(profile.get("degree"));List<Map<String,Object>> result=new ArrayList<>();String[] topics={"problem solving","professional communication","data literacy","software quality","career planning","ethical practice"};for(int index=0;index<QUESTIONS;index++){int answer=(level+index)%4;List<String> options=new ArrayList<>(List.of("Apply a clear, evidence-based approach","Skip planning and rely on assumptions","Use unverified information without review","Ignore stakeholder feedback"));Collections.rotate(options,answer);result.add(Map.of("id","L"+level+"Q"+(index+1),"focusArea",topics[index],"prompt","For a "+(role.isBlank()?"graduate role":role)+" candidate with a "+(degree.isBlank()?"university":degree)+" background, which action best demonstrates "+topics[index]+"?","options",options,"correctIndex",answer,"explanation","Strong career decisions use evidence, reflection and responsible communication."));}return result; }
  private static String label(int level){return level<=3?"Foundation":level<=7?"Professional": "Advanced";} private static String difficulty(int level){return level<=3?"Easy":level<=7?"Intermediate":"Hard";} private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception error){throw new ApiException(HttpStatus.BAD_REQUEST,"Assessment data is invalid");}} private List<Map<String,Object>> readList(String value){try{return json.readValue(value,new TypeReference<List<Map<String,Object>>>(){});}catch(Exception error){throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"Assessment question data is invalid");}} private List<String> readStrings(String value){try{return json.readValue(value,new TypeReference<List<String>>(){});}catch(Exception ignored){return List.of();}} private static String text(Object value){return value==null?"":String.valueOf(value).trim();} private static int number(Object value,int fallback){try{return value==null?fallback:Integer.parseInt(String.valueOf(value));}catch(NumberFormatException error){return fallback;}}
}
