package edu.uiu.aoop.careerforge.web;

import edu.uiu.aoop.careerforge.security.AppPrincipal;
import edu.uiu.aoop.careerforge.service.AuditService;
import java.time.*;
import java.sql.Timestamp;
import java.nio.charset.StandardCharsets;
import java.util.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/** Administrator-only operational APIs. SQL is kept here only for legacy-schema projections; write rules stay explicit. */
@RestController @RequestMapping("/admin") @PreAuthorize("hasRole('ADMIN')")
public class AdminController {
  private final JdbcTemplate jdbc;
  private final ObjectMapper json;
  private final AuditService audit;
  public AdminController(JdbcTemplate jdbc, ObjectMapper json, AuditService audit) { this.jdbc = jdbc; this.json = json; this.audit = audit; }
  private void admin(AppPrincipal p) { if (p.role().name().equals("admin")) return; throw new ApiException(HttpStatus.FORBIDDEN,"Administrator access required"); }

  @GetMapping("/users") List<Map<String,Object>> users(@AuthenticationPrincipal AppPrincipal p,@RequestParam(defaultValue="") String search) { admin(p); String q="%"+search.trim()+"%"; return jdbc.queryForList("SELECT u.id,u.name,u.email,u.status,u.created_at,p.university,p.readiness_score,p.profile_completion FROM users u LEFT JOIN student_profiles p ON p.user_id=u.id WHERE u.role='student' AND (u.name LIKE ? OR u.email LIKE ? OR p.university LIKE ?) ORDER BY u.created_at DESC",q,q,q); }
  @GetMapping("/users/{id}") Map<String,Object> user(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id) { admin(p); return one("SELECT u.id,u.name,u.email,u.status,u.last_login_at,u.created_at,u.updated_at,p.university,p.degree,p.graduation_year,p.target_role,p.career_interests,p.location,p.phone,p.bio,p.avatar_url,p.avatar_data,p.readiness_score,p.profile_completion FROM users u LEFT JOIN student_profiles p ON p.user_id=u.id WHERE u.id=? AND u.role='student'",id,"Student account not found"); }
  @PatchMapping("/users/{id}/status") Map<String,Object> userStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b) { admin(p); String value=String.valueOf(b.get("status")); if(!Set.of("active","suspended").contains(value))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid user status"); if(jdbc.update("UPDATE users SET status=? WHERE id=? AND role='student'",value,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Student account not found"); return Map.of("message","User status updated"); }

  @GetMapping("/jobs") List<Map<String,Object>> jobs(@AuthenticationPrincipal AppPrincipal p) { admin(p); return jdbc.queryForList("SELECT j.id,j.title,j.slug,j.description,j.responsibilities,j.requirements,j.category,j.employment_type,j.location,j.workplace_type,j.salary_min,j.salary_max,j.currency,j.status,j.expires_at,j.application_mode,j.external_apply_url,j.source_label,j.created_at,j.updated_at,c.name company_name,COALESCE((SELECT COUNT(*) FROM applications a WHERE a.job_id=j.id AND a.status<>'withdrawn'),0) application_count FROM jobs j JOIN companies c ON c.id=j.company_id ORDER BY j.created_at DESC"); }
  @PostMapping("/jobs") @Transactional Map<String,Object> createJob(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b) { admin(p); String company=required(b,"companyName"); String title=required(b,"title"); String description=required(b,"description"); String category=required(b,"category"); String location=required(b,"location"); String expiry=required(b,"expiresAt"); jdbc.update("INSERT INTO companies (name) VALUES (?) ON DUPLICATE KEY UPDATE name=VALUES(name)",company); Long companyId=jdbc.queryForObject("SELECT id FROM companies WHERE name=?",Long.class,company); String slug=(title+"-"+company+"-"+UUID.randomUUID()).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-"); jdbc.update("INSERT INTO jobs (company_id,title,slug,description,requirements,category,employment_type,location,workplace_type,status,expires_at,created_by,application_mode,external_apply_url,source_label) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",companyId,title,slug,description,text(b,"requirements"),category,value(b,"employmentType","Full-time"),location,value(b,"workplaceType","On-site"),value(b,"status","draft"),Timestamp.from(Instant.parse(expiry)),p.id(),value(b,"applicationMode","careerforge"),nullable(b,"externalApplyUrl"),nullable(b,"sourceLabel")); return Map.of("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class),"message","Job created"); }
  @PatchMapping("/jobs/{id}/status") Map<String,Object> jobStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String s=String.valueOf(b.get("status"));if(!Set.of("draft","pending","live","closed").contains(s))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid job status");if(jdbc.update("UPDATE jobs SET status=? WHERE id=?",s,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Job not found");return Map.of("message",s.equals("live")?"Job is visible to students":"Job is hidden from students");}
  @PatchMapping("/jobs/{id}") Map<String,Object> updateJob(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p); if(jdbc.update("UPDATE jobs SET title=?,description=?,requirements=?,category=?,location=?,employment_type=?,workplace_type=?,status=? WHERE id=?",required(b,"title"),required(b,"description"),text(b,"requirements"),required(b,"category"),required(b,"location"),value(b,"employmentType","Full-time"),value(b,"workplaceType","On-site"),value(b,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Job not found");return Map.of("message","Job updated");}
  @DeleteMapping("/jobs/{id}") Map<String,Object> deleteJob(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM jobs WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Job not found");return Map.of("message","Job deleted");}

  @GetMapping("/events") List<Map<String,Object>> events(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT e.*,COALESCE((SELECT COUNT(*) FROM event_registrations r WHERE r.event_id=e.id),0) registration_count FROM events e ORDER BY e.starts_at DESC");}
  @PostMapping("/events") Map<String,Object> createEvent(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b){admin(p);jdbc.update("INSERT INTO events (title,description,event_type,host,location,event_url,starts_at,ends_at,capacity,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)",required(b,"title"),nullable(b,"description"),required(b,"eventType"),required(b,"host"),nullable(b,"location"),nullable(b,"eventUrl"),Timestamp.from(Instant.parse(required(b,"startsAt"))),Timestamp.from(Instant.parse(required(b,"endsAt"))),number(b,"capacity"),value(b,"status","draft"),p.id());return Map.of("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class),"message","Event created");}
  @PatchMapping("/events/{id}/status") Map<String,Object> eventStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String s=String.valueOf(b.get("status"));if(!Set.of("draft","published","cancelled").contains(s))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid event status");if(jdbc.update("UPDATE events SET status=? WHERE id=?",s,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Event not found");return Map.of("message","Event status updated");}
  @PatchMapping("/events/{id}") Map<String,Object> updateEvent(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p); Instant starts=parseInstant(required(b,"startsAt")); Instant ends=parseInstant(required(b,"endsAt")); if(!ends.isAfter(starts))throw new ApiException(HttpStatus.BAD_REQUEST,"End time must be after start time"); Integer capacity=number(b,"capacity"); if(capacity!=null&&capacity<1)throw new ApiException(HttpStatus.BAD_REQUEST,"Capacity must be at least one"); if(jdbc.update("UPDATE events SET title=?,description=?,event_type=?,host=?,location=?,event_url=?,starts_at=?,ends_at=?,capacity=?,status=? WHERE id=?",required(b,"title"),nullable(b,"description"),required(b,"eventType"),required(b,"host"),nullable(b,"location"),nullable(b,"eventUrl"),Timestamp.from(starts),Timestamp.from(ends),capacity,value(b,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Event not found");return Map.of("message","Event updated");}
  @DeleteMapping("/events/{id}") Map<String,Object> deleteEvent(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM events WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Event not found");return Map.of("message","Event deleted");}

  @GetMapping("/assessments") List<Map<String,Object>> assessments(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT a.*,COUNT(DISTINCT q.id) question_count,COUNT(DISTINCT aa.id) attempt_count,ROUND(AVG(aa.percentage),1) average_score FROM assessments a LEFT JOIN questions q ON q.assessment_id=a.id LEFT JOIN assessment_attempts aa ON aa.assessment_id=a.id GROUP BY a.id ORDER BY a.created_at DESC");}
  @PostMapping("/assessments") Map<String,Object> createAssessment(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b){admin(p);jdbc.update("INSERT INTO assessments (title,description,category,difficulty,time_limit_minutes,passing_percentage,status,created_by) VALUES (?,?,?,?,?,?,?,?)",required(b,"title"),nullable(b,"description"),required(b,"category"),value(b,"difficulty","Beginner"),number(b,"timeLimitMinutes",15),number(b,"passingPercentage",60),value(b,"status","draft"),p.id());return Map.of("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class),"message","Assessment created");}
  @PatchMapping("/assessments/{id}") Map<String,Object> updateAssessment(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);if(jdbc.update("UPDATE assessments SET title=?,description=?,category=?,difficulty=?,time_limit_minutes=?,passing_percentage=?,status=? WHERE id=?",required(b,"title"),nullable(b,"description"),required(b,"category"),value(b,"difficulty","Beginner"),number(b,"timeLimitMinutes",15),number(b,"passingPercentage",60),value(b,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Assessment not found");return Map.of("message","Assessment updated");}
  @DeleteMapping("/assessments/{id}") Map<String,Object> deleteAssessment(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM assessments WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Assessment not found");return Map.of("message","Assessment deleted");}
  @GetMapping("/questions") List<Map<String,Object>> questions(@AuthenticationPrincipal AppPrincipal p){admin(p);List<Map<String,Object>> r=jdbc.queryForList("SELECT q.*,a.title assessment_title FROM questions q JOIN assessments a ON a.id=q.assessment_id ORDER BY q.created_at DESC");for(var row:r)row.put("options",jdbc.queryForList("SELECT id,option_text,is_correct,sort_order FROM question_options WHERE question_id=? ORDER BY sort_order",row.get("id")));return r;}
  @PostMapping("/questions") @Transactional Map<String,Object> createQuestion(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b){admin(p);long id=saveQuestion(b,null);return Map.of("id",id,"message","Question created");}
  @PatchMapping("/questions/{id}") @Transactional Map<String,Object> updateQuestion(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);saveQuestion(b,id);return Map.of("message","Question updated");}
  @DeleteMapping("/questions/{id}") Map<String,Object> deleteQuestion(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM questions WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Question not found");return Map.of("message","Question deleted");}
  @GetMapping("/applications") List<Map<String,Object>> applications(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT a.id,a.user_id,a.job_id,a.status,a.match_percentage,a.applied_at,u.name applicant_name,u.email applicant_email,sp.university,sp.degree,sp.readiness_score,j.title job_title,c.name company_name FROM applications a JOIN users u ON u.id=a.user_id LEFT JOIN student_profiles sp ON sp.user_id=u.id JOIN jobs j ON j.id=a.job_id JOIN companies c ON c.id=j.company_id ORDER BY a.applied_at DESC");}
  @GetMapping("/applications/{id}") Map<String,Object> application(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);Map<String,Object> result=one("SELECT a.*,u.name applicant_name,u.email applicant_email,sp.university,sp.degree,sp.graduation_year,sp.target_role,sp.location,sp.phone,sp.bio,sp.avatar_url,sp.avatar_data,sp.readiness_score,j.title job_title,c.name company_name FROM applications a JOIN users u ON u.id=a.user_id LEFT JOIN student_profiles sp ON sp.user_id=u.id JOIN jobs j ON j.id=a.job_id JOIN companies c ON c.id=j.company_id WHERE a.id=?",id,"Application not found"); result.put("has_resume_file",result.get("resume_file_data")!=null); result.remove("resume_file_data"); return result;}
  @GetMapping("/applications/{id}/resume-file") ResponseEntity<byte[]> resumeFile(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);Map<String,Object> row=one("SELECT resume_file_data,resume_file_type,resume_file_name FROM applications WHERE id=?",id,"Application not found");String data=Objects.toString(row.get("resume_file_data"),"");if(data.isBlank())throw new ApiException(HttpStatus.NOT_FOUND,"No uploaded resume is available");String encoded=data.contains(",")?data.substring(data.indexOf(',')+1):data;byte[] bytes;try{bytes=Base64.getDecoder().decode(encoded);}catch(IllegalArgumentException error){bytes=data.getBytes(StandardCharsets.UTF_8);}String type=Objects.toString(row.get("resume_file_type"),MediaType.APPLICATION_OCTET_STREAM_VALUE);String name=Objects.toString(row.get("resume_file_name"),"resume");return ResponseEntity.ok().contentType(MediaType.parseMediaType(type)).header("Content-Disposition","inline; filename=\""+name.replace("\"","")+"\"").body(bytes);}
  @PatchMapping("/applications/{id}/status") Map<String,Object> applicationStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String s=String.valueOf(b.get("status"));if(!Set.of("applied","in_review","assessment","interview","offer","rejected").contains(s))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid application status");if(jdbc.update("UPDATE applications SET status=? WHERE id=? AND status<>'withdrawn'",s,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Active application not found");return Map.of("message","Application status updated");}
  @GetMapping("/community") Map<String,Object> community(@AuthenticationPrincipal AppPrincipal p){admin(p);List<Map<String,Object>> posts=jdbc.queryForList("SELECT p.*,u.name author,u.email author_email,u.role author_role,sp.university,sp.avatar_url,(SELECT COUNT(*) FROM post_likes l WHERE l.post_id=p.id) likes,(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id AND c.status='visible') comments,(SELECT COUNT(*) FROM content_reports r WHERE r.post_id=p.id AND r.status='open') report_count FROM community_posts p JOIN users u ON u.id=p.user_id LEFT JOIN student_profiles sp ON sp.user_id=u.id ORDER BY p.created_at DESC LIMIT 250");Map<String,Object> stats=jdbc.queryForMap("SELECT COUNT(*) total,SUM(status='visible') visible,SUM(status='pending_review') pending,SUM(status='removed') removed,(SELECT COUNT(*) FROM content_reports WHERE status='open') openReports,SUM(created_at>=CURDATE()) postsToday FROM community_posts");return Map.of("posts",posts,"stats",stats);}
  @PatchMapping("/community/posts/{id}") @Transactional Map<String,Object> moderateCommunity(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String action=required(b,"action");if(!Set.of("approve","remove","restore","rescan").contains(action))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid moderation action");String reason=nullable(b,"reason");if(reason==null)throw new ApiException(HttpStatus.BAD_REQUEST,"A moderation reason is required");String status=action.equals("remove")?"removed":"visible";if(jdbc.update("UPDATE community_posts SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?",status,p.id(),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Post not found");jdbc.update("UPDATE content_reports SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE post_id=? AND status='open'",action.equals("remove")?"actioned":"dismissed",p.id(),id);audit.record(p.id(),"community."+action,"community_post",id,reason,Map.of("status",status));return Map.of("message",action.equals("remove")?"Post removed from the community":"Post moderation updated");}
  @GetMapping("/settings") Map<String,Object> settings(@AuthenticationPrincipal AppPrincipal p){admin(p);return Map.of("settings",readSettings(),"integrations",Map.of("database","connected","aiService","external","emailService","environment"));}
  @PatchMapping("/settings") Map<String,Object> saveSettings(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object> body){admin(p);Map<String,Object> settings=mergeSettings(readSettings(),body);try{jdbc.update("INSERT INTO platform_settings (setting_key,setting_value,updated_by) VALUES ('platform',CAST(? AS JSON),?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)",json.writeValueAsString(settings),p.id());}catch(Exception error){throw new ApiException(HttpStatus.BAD_REQUEST,"Settings could not be saved");}return Map.of("settings",settings,"message","System settings saved");}
  @GetMapping("/resources") List<Map<String,Object>> resources(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT * FROM learning_resources ORDER BY created_at DESC");}
  @PostMapping("/resources") Map<String,Object> createResource(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b){admin(p);jdbc.update("INSERT INTO learning_resources (title,description,category,difficulty,resource_type,resource_url,thumbnail_url,estimated_minutes,featured,status) VALUES (?,?,?,?,?,?,?,?,?,?)",required(b,"title"),nullable(b,"description"),required(b,"category"),value(b,"difficulty","Beginner"),value(b,"resourceType","article"),required(b,"resourceUrl"),nullable(b,"thumbnailUrl"),number(b,"estimatedMinutes"),Boolean.TRUE.equals(b.get("featured")),value(b,"status","draft"));return Map.of("message","Resource created");}
  @PatchMapping("/resources/{id}") Map<String,Object> updateResource(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);if(jdbc.update("UPDATE learning_resources SET title=?,description=?,category=?,difficulty=?,resource_type=?,resource_url=?,thumbnail_url=?,estimated_minutes=?,featured=?,status=? WHERE id=?",required(b,"title"),nullable(b,"description"),required(b,"category"),value(b,"difficulty","Beginner"),value(b,"resourceType","article"),required(b,"resourceUrl"),nullable(b,"thumbnailUrl"),number(b,"estimatedMinutes"),Boolean.TRUE.equals(b.get("featured")),value(b,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Resource not found");return Map.of("message","Resource updated");}
  @DeleteMapping("/resources/{id}") Map<String,Object> deleteResource(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM learning_resources WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Resource not found");return Map.of("message","Resource deleted");}
  private long saveQuestion(Map<String,Object> body,Long id){Long assessmentId=longValue(body,"assessmentId");String prompt=required(body,"prompt");List<Map<String,Object>> options=options(body.get("options"));if(options.size()<2||options.stream().filter(x->Boolean.TRUE.equals(x.get("isCorrect"))).count()!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"Provide at least two options and exactly one correct answer");if(jdbc.queryForObject("SELECT COUNT(*) FROM assessments WHERE id=?",Integer.class,assessmentId)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Assessment not found");if(id==null){jdbc.update("INSERT INTO questions (assessment_id,prompt,question_type,difficulty,explanation,points,status) VALUES (?,?,?,?,?,?,?)",assessmentId,prompt,value(body,"questionType","multiple_choice"),value(body,"difficulty","Beginner"),nullable(body,"explanation"),decimal(body,"points",1d),value(body,"status","draft"));id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);}else{if(jdbc.update("UPDATE questions SET assessment_id=?,prompt=?,question_type=?,difficulty=?,explanation=?,points=?,status=? WHERE id=?",assessmentId,prompt,value(body,"questionType","multiple_choice"),value(body,"difficulty","Beginner"),nullable(body,"explanation"),decimal(body,"points",1d),value(body,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Question not found");jdbc.update("DELETE FROM question_options WHERE question_id=?",id);}int order=0;for(Map<String,Object> option:options)jdbc.update("INSERT INTO question_options (question_id,option_text,is_correct,sort_order) VALUES (?,?,?,?)",id,required(option,"text"),Boolean.TRUE.equals(option.get("isCorrect")),order++);return id;}
  @SuppressWarnings("unchecked") private List<Map<String,Object>> options(Object raw){if(!(raw instanceof List<?> list))return List.of();List<Map<String,Object>> result=new ArrayList<>();for(Object item:list)if(item instanceof Map<?,?> map){Map<String,Object> option=new LinkedHashMap<>();for(var entry:map.entrySet())option.put(String.valueOf(entry.getKey()),entry.getValue());if(!text(option,"text").isBlank())result.add(option);}return result;}
  private Map<String,Object> readSettings(){Map<String,Object> defaults=new LinkedHashMap<>();defaults.put("general",Map.of("platformName","CareerForge","supportEmail","support@careerforge.local","timezone","Asia/Dhaka","locale","English (Bangladesh)"));defaults.put("features",Map.of("registrationEnabled",true,"coverLetterEnabled",true,"communityPostingEnabled",true,"maintenanceMode",false));defaults.put("security",Map.of("minimumPasswordLength",8,"requireUppercase",false,"requireNumber",false,"sessionHours",168));defaults.put("email",Map.of("senderName","CareerForge","replyTo","support@careerforge.local","welcomeSubject","Welcome to CareerForge","welcomeBody","","applicationSubject","Application received","applicationBody",""));defaults.put("integrations",Map.of("supportPortalUrl","","careerPageUrl","","webhookUrl","","webhookEnabled",false));defaults.put("ai",Map.of("jobRecommendationsEnabled",true,"contentModerationEnabled",true,"moderationThreshold",38,"coverLetterTone","Professional"));try{String stored=jdbc.query("SELECT setting_value FROM platform_settings WHERE setting_key='platform'",rs->rs.next()?rs.getString(1):null);if(stored==null)return defaults;return mergeSettings(defaults,json.readValue(stored,new TypeReference<Map<String,Object>>(){}));}catch(Exception ignored){return defaults;}}
  @SuppressWarnings("unchecked") private Map<String,Object> mergeSettings(Map<String,Object> base,Map<String,Object> patch){Map<String,Object> result=new LinkedHashMap<>(base);for(var entry:patch.entrySet()){Object current=result.get(entry.getKey());if(current instanceof Map<?,?>&&entry.getValue() instanceof Map<?,?>){Map<String,Object> nested=new LinkedHashMap<>();((Map<?,?>)current).forEach((k,v)->nested.put(String.valueOf(k),v));Map<String,Object> changes=new LinkedHashMap<>();((Map<?,?>)entry.getValue()).forEach((k,v)->changes.put(String.valueOf(k),v));result.put(entry.getKey(),mergeSettings(nested,changes));}else result.put(entry.getKey(),entry.getValue());}return result;}
  private Map<String,Object> one(String sql,Long id,String missing){List<Map<String,Object>> r=jdbc.queryForList(sql,id);if(r.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,missing);return r.getFirst();} private static String required(Map<String,Object>b,String k){String v=text(b,k);if(v.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,k+" is required");return v;} private static String text(Map<String,Object>b,String k){return b.get(k)==null?"":String.valueOf(b.get(k)).trim();} private static String nullable(Map<String,Object>b,String k){String v=text(b,k);return v.isBlank()?null:v;} private static String value(Map<String,Object>b,String k,String fallback){String v=text(b,k);return v.isBlank()?fallback:v;} private static Integer number(Map<String,Object>b,String k){String v=text(b,k);return v.isBlank()?null:Integer.valueOf(v);} private static Integer number(Map<String,Object>b,String k,int fallback){String v=text(b,k);return v.isBlank()?fallback:Integer.valueOf(v);}
  private static Long longValue(Map<String,Object> b,String key){try{return Long.valueOf(required(b,key));}catch(NumberFormatException error){throw new ApiException(HttpStatus.BAD_REQUEST,key+" must be a number");}} private static double decimal(Map<String,Object> b,String key,double fallback){try{String value=text(b,key);return value.isBlank()?fallback:Double.parseDouble(value);}catch(NumberFormatException error){throw new ApiException(HttpStatus.BAD_REQUEST,key+" must be a number");}} private static Instant parseInstant(String value){try{return Instant.parse(value);}catch(Exception error){throw new ApiException(HttpStatus.BAD_REQUEST,"Enter a valid ISO date and time");}}
}
