package edu.uiu.aoop.careerforge.web;

import edu.uiu.aoop.careerforge.security.AppPrincipal;
import java.time.*;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/** Administrator-only operational APIs. SQL is kept here only for legacy-schema projections; write rules stay explicit. */
@RestController @RequestMapping("/admin")
public class AdminController {
  private final JdbcTemplate jdbc;
  public AdminController(JdbcTemplate jdbc) { this.jdbc = jdbc; }
  private void admin(AppPrincipal p) { if (p.role().name().equals("admin")) return; throw new ApiException(HttpStatus.FORBIDDEN,"Administrator access required"); }

  @GetMapping("/users") List<Map<String,Object>> users(@AuthenticationPrincipal AppPrincipal p,@RequestParam(defaultValue="") String search) { admin(p); String q="%"+search.trim()+"%"; return jdbc.queryForList("SELECT u.id,u.name,u.email,u.status,u.created_at,p.university,p.readiness_score,p.profile_completion FROM users u LEFT JOIN student_profiles p ON p.user_id=u.id WHERE u.role='student' AND (u.name LIKE ? OR u.email LIKE ? OR p.university LIKE ?) ORDER BY u.created_at DESC",q,q,q); }
  @GetMapping("/users/{id}") Map<String,Object> user(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id) { admin(p); return one("SELECT u.id,u.name,u.email,u.status,u.last_login_at,u.created_at,u.updated_at,p.university,p.degree,p.graduation_year,p.target_role,p.career_interests,p.location,p.phone,p.bio,p.avatar_url,p.avatar_data,p.readiness_score,p.profile_completion FROM users u LEFT JOIN student_profiles p ON p.user_id=u.id WHERE u.id=? AND u.role='student'",id,"Student account not found"); }
  @PatchMapping("/users/{id}/status") Map<String,Object> userStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b) { admin(p); String value=String.valueOf(b.get("status")); if(!Set.of("active","suspended").contains(value))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid user status"); if(jdbc.update("UPDATE users SET status=? WHERE id=? AND role='student'",value,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Student account not found"); return Map.of("message","User status updated"); }

  @GetMapping("/jobs") List<Map<String,Object>> jobs(@AuthenticationPrincipal AppPrincipal p) { admin(p); return jdbc.queryForList("SELECT j.id,j.title,j.slug,j.description,j.responsibilities,j.requirements,j.category,j.employment_type,j.location,j.workplace_type,j.salary_min,j.salary_max,j.currency,j.status,j.expires_at,j.application_mode,j.external_apply_url,j.source_label,j.created_at,j.updated_at,c.name company_name,COALESCE((SELECT COUNT(*) FROM applications a WHERE a.job_id=j.id AND a.status<>'withdrawn'),0) application_count FROM jobs j JOIN companies c ON c.id=j.company_id ORDER BY j.created_at DESC"); }
  @PostMapping("/jobs") @Transactional Map<String,Object> createJob(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b) { admin(p); String company=required(b,"companyName"); String title=required(b,"title"); String description=required(b,"description"); String category=required(b,"category"); String location=required(b,"location"); String expiry=required(b,"expiresAt"); jdbc.update("INSERT INTO companies (name) VALUES (?) ON DUPLICATE KEY UPDATE name=VALUES(name)",company); Long companyId=jdbc.queryForObject("SELECT id FROM companies WHERE name=?",Long.class,company); String slug=(title+"-"+company+"-"+UUID.randomUUID()).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-"); jdbc.update("INSERT INTO jobs (company_id,title,slug,description,requirements,category,employment_type,location,workplace_type,status,expires_at,created_by,application_mode,external_apply_url,source_label) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",companyId,title,slug,description,text(b,"requirements"),category,value(b,"employmentType","Full-time"),location,value(b,"workplaceType","On-site"),value(b,"status","draft"),Timestamp.from(Instant.parse(expiry)),p.id(),value(b,"applicationMode","careerforge"),nullable(b,"externalApplyUrl"),nullable(b,"sourceLabel")); return Map.of("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class),"message","Job created"); }
  @PatchMapping("/jobs/{id}/status") Map<String,Object> jobStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String s=String.valueOf(b.get("status"));if(!Set.of("draft","pending","live","closed").contains(s))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid job status");if(jdbc.update("UPDATE jobs SET status=? WHERE id=?",s,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Job not found");return Map.of("message",s.equals("live")?"Job is visible to students":"Job is hidden from students");}
  @PatchMapping("/jobs/{id}") Map<String,Object> updateJob(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p); if(jdbc.update("UPDATE jobs SET title=?,description=?,requirements=?,category=?,location=?,employment_type=?,workplace_type=?,status=? WHERE id=?",required(b,"title"),required(b,"description"),text(b,"requirements"),required(b,"category"),required(b,"location"),value(b,"employmentType","Full-time"),value(b,"workplaceType","On-site"),value(b,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Job not found");return Map.of("message","Job updated");}
  @DeleteMapping("/jobs/{id}") Map<String,Object> deleteJob(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM jobs WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Job not found");return Map.of("message","Job deleted");}

  @GetMapping("/events") List<Map<String,Object>> events(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT e.*,COALESCE((SELECT COUNT(*) FROM event_registrations r WHERE r.event_id=e.id),0) registration_count FROM events e ORDER BY e.starts_at DESC");}
  @PostMapping("/events") Map<String,Object> createEvent(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b){admin(p);jdbc.update("INSERT INTO events (title,description,event_type,host,location,event_url,starts_at,ends_at,capacity,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)",required(b,"title"),nullable(b,"description"),required(b,"eventType"),required(b,"host"),nullable(b,"location"),nullable(b,"eventUrl"),Timestamp.from(Instant.parse(required(b,"startsAt"))),Timestamp.from(Instant.parse(required(b,"endsAt"))),number(b,"capacity"),value(b,"status","draft"),p.id());return Map.of("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class),"message","Event created");}
  @PatchMapping("/events/{id}/status") Map<String,Object> eventStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String s=String.valueOf(b.get("status"));if(!Set.of("draft","published","cancelled").contains(s))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid event status");if(jdbc.update("UPDATE events SET status=? WHERE id=?",s,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Event not found");return Map.of("message","Event status updated");}
  @DeleteMapping("/events/{id}") Map<String,Object> deleteEvent(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM events WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Event not found");return Map.of("message","Event deleted");}

  @GetMapping("/assessments") List<Map<String,Object>> assessments(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT a.*,COUNT(DISTINCT q.id) question_count,COUNT(DISTINCT aa.id) attempt_count,ROUND(AVG(aa.percentage),1) average_score FROM assessments a LEFT JOIN questions q ON q.assessment_id=a.id LEFT JOIN assessment_attempts aa ON aa.assessment_id=a.id GROUP BY a.id ORDER BY a.created_at DESC");}
  @PostMapping("/assessments") Map<String,Object> createAssessment(@AuthenticationPrincipal AppPrincipal p,@RequestBody Map<String,Object>b){admin(p);jdbc.update("INSERT INTO assessments (title,description,category,difficulty,time_limit_minutes,passing_percentage,status,created_by) VALUES (?,?,?,?,?,?,?,?)",required(b,"title"),nullable(b,"description"),required(b,"category"),value(b,"difficulty","Beginner"),number(b,"timeLimitMinutes",15),number(b,"passingPercentage",60),value(b,"status","draft"),p.id());return Map.of("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class),"message","Assessment created");}
  @PatchMapping("/assessments/{id}") Map<String,Object> updateAssessment(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);if(jdbc.update("UPDATE assessments SET title=?,description=?,category=?,difficulty=?,time_limit_minutes=?,passing_percentage=?,status=? WHERE id=?",required(b,"title"),nullable(b,"description"),required(b,"category"),value(b,"difficulty","Beginner"),number(b,"timeLimitMinutes",15),number(b,"passingPercentage",60),value(b,"status","draft"),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Assessment not found");return Map.of("message","Assessment updated");}
  @DeleteMapping("/assessments/{id}") Map<String,Object> deleteAssessment(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id){admin(p);if(jdbc.update("DELETE FROM assessments WHERE id=?",id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Assessment not found");return Map.of("message","Assessment deleted");}
  @GetMapping("/questions") List<Map<String,Object>> questions(@AuthenticationPrincipal AppPrincipal p){admin(p);List<Map<String,Object>> r=jdbc.queryForList("SELECT q.*,a.title assessment_title FROM questions q JOIN assessments a ON a.id=q.assessment_id ORDER BY q.created_at DESC");for(var row:r)row.put("options",jdbc.queryForList("SELECT id,option_text,is_correct,sort_order FROM question_options WHERE question_id=? ORDER BY sort_order",row.get("id")));return r;}
  @GetMapping("/applications") List<Map<String,Object>> applications(@AuthenticationPrincipal AppPrincipal p){admin(p);return jdbc.queryForList("SELECT a.id,a.user_id,a.job_id,a.status,a.match_percentage,a.applied_at,u.name applicant_name,u.email applicant_email,sp.university,sp.degree,sp.readiness_score,j.title job_title,c.name company_name FROM applications a JOIN users u ON u.id=a.user_id LEFT JOIN student_profiles sp ON sp.user_id=u.id JOIN jobs j ON j.id=a.job_id JOIN companies c ON c.id=j.company_id ORDER BY a.applied_at DESC");}
  @PatchMapping("/applications/{id}/status") Map<String,Object> applicationStatus(@AuthenticationPrincipal AppPrincipal p,@PathVariable Long id,@RequestBody Map<String,Object>b){admin(p);String s=String.valueOf(b.get("status"));if(!Set.of("applied","in_review","assessment","interview","offer","rejected").contains(s))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid application status");if(jdbc.update("UPDATE applications SET status=? WHERE id=? AND status<>'withdrawn'",s,id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Active application not found");return Map.of("message","Application status updated");}
  private Map<String,Object> one(String sql,Long id,String missing){List<Map<String,Object>> r=jdbc.queryForList(sql,id);if(r.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,missing);return r.getFirst();} private static String required(Map<String,Object>b,String k){String v=text(b,k);if(v.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,k+" is required");return v;} private static String text(Map<String,Object>b,String k){return b.get(k)==null?"":String.valueOf(b.get(k)).trim();} private static String nullable(Map<String,Object>b,String k){String v=text(b,k);return v.isBlank()?null:v;} private static String value(Map<String,Object>b,String k,String fallback){String v=text(b,k);return v.isBlank()?fallback:v;} private static Integer number(Map<String,Object>b,String k){String v=text(b,k);return v.isBlank()?null:Integer.valueOf(v);} private static Integer number(Map<String,Object>b,String k,int fallback){String v=text(b,k);return v.isBlank()?fallback:Integer.valueOf(v);}
}
