package edu.uiu.aoop.careerforge.service;
import edu.uiu.aoop.careerforge.domain.*; import edu.uiu.aoop.careerforge.event.CareerMilestoneEvent; import edu.uiu.aoop.careerforge.repository.UserRepository; import edu.uiu.aoop.careerforge.security.JwtService; import edu.uiu.aoop.careerforge.web.ApiException; import java.util.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AuthService {
 private final UserRepository users; private final PasswordEncoder passwords; private final JwtService jwt; private final ApplicationEventPublisher events;
 public AuthService(UserRepository users,PasswordEncoder passwords,JwtService jwt,ApplicationEventPublisher events){this.users=users;this.passwords=passwords;this.jwt=jwt;this.events=events;}
 @Transactional public Map<String,Object> register(String name,String email,String password){ String normalized=normalizeEmail(email); if(users.existsByEmailIgnoreCase(normalized)) throw new ApiException(HttpStatus.CONFLICT,"An account already uses this email"); validatePassword(password); User user=new User(clean(name,120),normalized,passwords.encode(password),Role.student); user.setProfile(new StudentProfile()); users.save(user); return session(user); }
 @Transactional public Map<String,Object> login(String email,String password,String requestedRole){ User user=users.findByEmailIgnoreCase(normalizeEmail(email)).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Invalid email or password")); if(!passwords.matches(password,user.getPasswordHash())) throw new ApiException(HttpStatus.UNAUTHORIZED,"Invalid email or password"); if(requestedRole!=null&&!requestedRole.isBlank()&&!user.getRole().name().equals(requestedRole)) throw new ApiException(HttpStatus.FORBIDDEN,"Use the correct sign-in portal for this account"); if(user.getStatus()!=UserStatus.active) throw new ApiException(HttpStatus.FORBIDDEN,"This account is suspended"); user.recordLogin(); return session(user); }
 @Transactional(readOnly=true) public User require(Long id){return users.findById(id).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Session user no longer exists"));}
 public Map<String,Object> session(User user){return Map.of("token",jwt.issue(user),"user",profile(user));}
 @Transactional(readOnly=true) public Map<String,Object> profile(User u){ u=users.findById(u.getId()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Session user no longer exists")); Map<String,Object> result=new LinkedHashMap<>(); result.put("id",u.getId()); result.put("name",u.getName()); result.put("email",u.getEmail()); result.put("role",u.getRole().name()); result.put("status",u.getStatus().name()); if(u.getProfile()!=null){StudentProfile p=u.getProfile(); result.put("university",p.getUniversity());result.put("degree",p.getDegree());result.put("graduation_year",p.getGraduationYear());result.put("target_role",p.getTargetRole());result.put("career_interests",parseJsonArray(p.getCareerInterests()));result.put("location",p.getLocation());result.put("phone",p.getPhone());result.put("bio",p.getBio());result.put("avatar_url",p.getAvatarUrl());result.put("avatar_data",p.getAvatarData());result.put("resume_url",p.getResumeUrl());result.put("readiness_score",p.getReadinessScore());result.put("profile_completion",p.getProfileCompletion());} return result; }
 @Transactional public Map<String,Object> updateProfile(Long id,Map<String,Object> body){User u=require(id); if(body.containsKey("name"))u.rename(clean(String.valueOf(body.get("name")),120)); if(body.containsKey("email")){String email=normalizeEmail(String.valueOf(body.get("email"))); users.findByEmailIgnoreCase(email).filter(other->!other.getId().equals(id)).ifPresent(other->{throw new ApiException(HttpStatus.CONFLICT,"An account already uses this email");});u.changeEmail(email);} if(u.getRole()==Role.student){StudentProfile p=u.getProfile(); if(p==null){p=new StudentProfile();u.setProfile(p);} p.update(text(body,"university"),text(body,"degree"),integer(body,"graduation_year"),text(body,"target_role"),text(body,"location"),text(body,"phone"),text(body,"bio"),jsonArray(body.get("career_interests")),text(body,"avatar_data"));if(p.getProfileCompletion()>=100)events.publishEvent(new CareerMilestoneEvent(id,CareerMilestoneEvent.Type.PROFILE_COMPLETED));} return profile(u); }
 private static String normalizeEmail(String value){String email=value==null?"":value.trim().toLowerCase(Locale.ROOT);if(!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))throw new ApiException(HttpStatus.BAD_REQUEST,"Enter a valid email address");return email;} private static String clean(String value,int max){String result=value==null?"":value.trim();if(result.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Name is required");return result.substring(0,Math.min(result.length(),max));} private static void validatePassword(String value){if(value==null||value.length()<8)throw new ApiException(HttpStatus.BAD_REQUEST,"Password must contain at least 8 characters");} private static String text(Map<String,Object>b,String k){Object x=b.get(k);return x==null?null:String.valueOf(x).trim();} private static Integer integer(Map<String,Object>b,String k){try{Object x=b.get(k);return x==null?null:Integer.valueOf(String.valueOf(x));}catch(NumberFormatException e){throw new ApiException(HttpStatus.BAD_REQUEST,"Graduation year must be a number");}} private static String jsonArray(Object value){if(value instanceof Collection<?> c)return "["+c.stream().filter(Objects::nonNull).map(v->"\""+String.valueOf(v).replace("\"","\\\"")+"\"").collect(java.util.stream.Collectors.joining(","))+"]";return value==null?"[]":String.valueOf(value);} private static List<String> parseJsonArray(String json){if(json==null)return List.of();return Arrays.stream(json.replaceAll("[\\[\\]\"]","").split(",")).map(String::trim).filter(s->!s.isBlank()).toList();}
}
