package edu.uiu.aoop.careerforge.service;
import edu.uiu.aoop.careerforge.domain.Role; import edu.uiu.aoop.careerforge.web.ApiException; import java.sql.Timestamp; import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class CommunityService {
 private final JdbcTemplate jdbc; private final boolean postingEnabled; public CommunityService(JdbcTemplate jdbc,@org.springframework.beans.factory.annotation.Value("${careerforge.features.community-posting-enabled}") boolean postingEnabled){this.jdbc=jdbc;this.postingEnabled=postingEnabled;}
 public Map<String,Object> postingStatus(Long userId,Role role){Map<String,Object> result=new LinkedHashMap<>();if(role==Role.admin){result.put("canPost",true);result.put("nextPostAt",null);result.put("cooldownHours",12);return result;}if(!postingEnabled){result.put("canPost",false);result.put("nextPostAt",null);result.put("cooldownHours",12);result.put("disabled",true);result.put("reason","Student community posting is currently disabled by an administrator");return result;}Timestamp next=jdbc.query("SELECT DATE_ADD(MAX(created_at), INTERVAL 12 HOUR) FROM community_posts WHERE user_id=?",rs->rs.next()?rs.getTimestamp(1):null,userId);boolean can=next==null||next.toInstant().isBefore(Instant.now());result.put("canPost",can);result.put("nextPostAt",next==null?null:next.toInstant());result.put("cooldownHours",12);return result;}
 public List<Map<String,Object>> posts(Long userId,Role role){return jdbc.queryForList("SELECT p.id,p.user_id,p.content,p.media_url,p.link_url,p.tags,p.share_count,p.status,p.created_at,u.name author,u.role author_role,sp.university,sp.avatar_url,(SELECT COUNT(*) FROM post_likes l WHERE l.post_id=p.id) likes,(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id AND c.status='visible') comments,EXISTS(SELECT 1 FROM post_likes mine WHERE mine.post_id=p.id AND mine.user_id=?) liked,(p.user_id=?) is_owner FROM community_posts p JOIN users u ON u.id=p.user_id LEFT JOIN student_profiles sp ON sp.user_id=u.id WHERE p.status='visible' OR (p.user_id=? AND p.status='pending_review') ORDER BY p.created_at DESC LIMIT 100",userId,userId,userId);}
 @Transactional public Map<String,Object> create(Long userId,Role role,String author,Map<String,Object> body){String content=text(body.get("content"),5000);if(content.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Post content is required");if(role==Role.student){Map<String,Object> status=postingStatus(userId,role);if(Boolean.FALSE.equals(status.get("canPost")))throw new ApiException(HttpStatus.TOO_MANY_REQUESTS,"Students can publish one community post every 12 hours");}String link=text(body.get("linkUrl"),500);if(!link.isBlank()&&!link.matches("https?://.+"))throw new ApiException(HttpStatus.BAD_REQUEST,"Resource link must be a valid http or https URL");String tags=jsonArray(body.get("tags"));jdbc.update("INSERT INTO community_posts (user_id,content,link_url,tags,status,risk_score,risk_label) VALUES (?,?,?,?, 'visible',0,'safe')",userId,content,link.isBlank()?null:link,tags);Long id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);Map<String,Object> post=new LinkedHashMap<>();post.put("id",id);post.put("user_id",userId);post.put("content",content);post.put("link_url",link.isBlank()?null:link);post.put("tags",tags);post.put("status","visible");post.put("author",author);post.put("author_role",role.name());post.put("likes",0);post.put("comments",0);post.put("liked",0);post.put("is_owner",1);post.put("created_at",Instant.now());Map<String,Object> response=new LinkedHashMap<>();response.put("id",id);response.put("status","visible");response.put("post",post);response.put("nextPostAt",role==Role.student?Instant.now().plus(12,ChronoUnit.HOURS):null);response.put("message","Post published");return response;}
 @Transactional public Map<String,Object> like(Long userId,Long postId){requireVisible(postId);Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM post_likes WHERE post_id=? AND user_id=?",Integer.class,postId,userId);if(count!=null&&count>0){jdbc.update("DELETE FROM post_likes WHERE post_id=? AND user_id=?",postId,userId);}else jdbc.update("INSERT INTO post_likes (post_id,user_id) VALUES (?,?)",postId,userId);Integer likes=jdbc.queryForObject("SELECT COUNT(*) FROM post_likes WHERE post_id=?",Integer.class,postId);return Map.of("liked",count==null||count==0,"likes",likes);}
 public List<Map<String,Object>> comments(Long userId,Long postId){requireVisible(postId);return jdbc.queryForList("SELECT c.id,c.post_id,c.user_id,c.content,c.created_at,u.name author,u.role author_role,sp.avatar_url,(c.user_id=?) is_owner FROM comments c JOIN users u ON u.id=c.user_id LEFT JOIN student_profiles sp ON sp.user_id=u.id WHERE c.post_id=? AND c.status='visible' ORDER BY c.created_at",userId,postId);}
 @Transactional public Map<String,Object> comment(Long userId,Role role,String name,Long postId,String content){requireVisible(postId);content=text(content,1500);if(content.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Comment content is required");jdbc.update("INSERT INTO comments (post_id,user_id,content,status) VALUES (?,?,?,'visible')",postId,userId,content);Long id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);return Map.of("id",id,"post_id",postId,"user_id",userId,"content",content,"author",name,"author_role",role.name(),"is_owner",1,"created_at",Instant.now());}
 @Transactional public Map<String,Object> deletePost(Long actor,Role role,Long id){Integer owner=jdbc.query("SELECT user_id FROM community_posts WHERE id=?",rs->rs.next()?rs.getInt(1):null,id);if(owner==null)throw new ApiException(HttpStatus.NOT_FOUND,"Post not found");if(owner.longValue()!=actor&&role!=Role.admin)throw new ApiException(HttpStatus.FORBIDDEN,"You cannot remove this post");jdbc.update("UPDATE community_posts SET status='removed',reviewed_by=?,reviewed_at=NOW() WHERE id=?",role==Role.admin?actor:null,id);return Map.of("message","Post removed");}
 @Transactional public Map<String,Object> deleteComment(Long actor,Role role,Long id){Integer owner=jdbc.query("SELECT user_id FROM comments WHERE id=?",rs->rs.next()?rs.getInt(1):null,id);if(owner==null)throw new ApiException(HttpStatus.NOT_FOUND,"Comment not found");if(owner.longValue()!=actor&&role!=Role.admin)throw new ApiException(HttpStatus.FORBIDDEN,"You cannot remove this comment");jdbc.update("UPDATE comments SET status='removed' WHERE id=?",id);return Map.of("message","Comment removed");}
 @Transactional public Map<String,Object> share(Long actor,Long postId){requireVisible(postId);Integer exists=jdbc.queryForObject("SELECT COUNT(*) FROM post_shares WHERE post_id=? AND user_id=?",Integer.class,postId,actor);if(exists==null||exists==0){jdbc.update("INSERT INTO post_shares (post_id,user_id) VALUES (?,?)",postId,actor);jdbc.update("UPDATE community_posts SET share_count=share_count+1 WHERE id=?",postId);}Integer shares=jdbc.queryForObject("SELECT share_count FROM community_posts WHERE id=?",Integer.class,postId);return Map.of("shared",true,"share_count",shares);}
 @Transactional public Map<String,Object> report(Long actor,Long postId,Map<String,Object> body){requireVisible(postId);String reason=text(body.get("reason"),120);if(!Set.of("spam","fraud","harassment","misinformation","other").contains(reason))throw new ApiException(HttpStatus.BAD_REQUEST,"Choose a valid report reason");jdbc.update("INSERT INTO content_reports (post_id,reporter_id,reason,details,status) VALUES (?,?,?,?, 'open')",postId,actor,reason,text(body.get("details"),1000));Long id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);return Map.of("id",id,"message","Report sent to administrators");}
 private void requireVisible(Long id){Integer found=jdbc.query("SELECT id FROM community_posts WHERE id=? AND status='visible'",rs->rs.next()?rs.getInt(1):null,id);if(found==null)throw new ApiException(HttpStatus.NOT_FOUND,"Post not found");} private static String text(Object x,int max){return x==null?"":String.valueOf(x).trim().substring(0,Math.min(String.valueOf(x).trim().length(),max));} private static String jsonArray(Object x){if(x instanceof Collection<?> c)return "["+c.stream().map(v->"\""+String.valueOf(v).replace("\"","\\\"")+"\"").collect(java.util.stream.Collectors.joining(","))+"]";return x==null?null:String.valueOf(x);}
}
