package edu.uiu.aoop.careerforge.service;
import edu.uiu.aoop.careerforge.domain.*; import edu.uiu.aoop.careerforge.repository.*; import edu.uiu.aoop.careerforge.web.ApiException; import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class JobService {
 private final JobRepository jobs; private final UserRepository users; private final JobApplicationRepository applications; private final JobMatchingStrategy matcher; private final JdbcTemplate jdbc;
 public JobService(JobRepository jobs,UserRepository users,JobApplicationRepository applications,JobMatchingStrategy matcher,JdbcTemplate jdbc){this.jobs=jobs;this.users=users;this.applications=applications;this.matcher=matcher;this.jdbc=jdbc;}
 @Transactional(readOnly=true) public List<Map<String,Object>> recommendations(Long userId){User user=users.findById(userId).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Session user no longer exists"));List<String> skills=jdbc.query("SELECT s.name FROM user_skills us JOIN skills s ON s.id=us.skill_id WHERE us.user_id=?",(rs,n)->rs.getString(1),userId);return jobs.findByStatusOrderByCreatedAtDesc(JobStatus.live).stream().filter(Job::visibleNow).map(job->{var m=matcher.score(user.getProfile(),job,skills);return jobDto(job,m.percentage(),m.reasons());}).toList();}
 @Transactional public Map<String,Object> apply(Long userId,Long jobId,Map<String,Object> body){User user=users.findById(userId).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Session user no longer exists"));Job job=jobs.findById(jobId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Job not found"));if(user.getRole()!=Role.student)throw new ApiException(HttpStatus.FORBIDDEN,"Only students can apply for jobs");if(!job.visibleNow())throw new ApiException(HttpStatus.CONFLICT,"This job is no longer accepting applications");if(!"careerforge".equalsIgnoreCase(job.getApplicationMode()))throw new ApiException(HttpStatus.CONFLICT,"This opportunity uses an external application link");if(applications.findByStudentIdAndJobId(userId,jobId).isPresent())throw new ApiException(HttpStatus.CONFLICT,"You already applied to this job");var match=matcher.score(user.getProfile(),job,List.of());String cover=body.get("coverLetter")==null?null:String.valueOf(body.get("coverLetter"));String snapshot=body.get("resumeSnapshot")==null?null:body.get("resumeSnapshot").toString();JobApplication application=applications.save(new JobApplication(user,job,(double)match.percentage(),cover,snapshot));return Map.of("id",application.getId(),"message","Application submitted","status",application.getStatus().name());}
 @Transactional public Map<String,Object> withdraw(Long userId,Long applicationId){JobApplication application=applications.findById(applicationId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Application not found"));if(!application.getStudent().getId().equals(userId))throw new ApiException(HttpStatus.FORBIDDEN,"You can only cancel your own application");application.transitionTo(ApplicationStatus.withdrawn);return Map.of("message","Application cancelled","status","withdrawn");}
 @Transactional(readOnly=true) public List<Map<String,Object>> myApplications(Long userId){return applications.findByStudentIdOrderByAppliedAtDesc(userId).stream().map(a->{Map<String,Object> r=new LinkedHashMap<>();r.put("id",a.getId());r.put("job_id",a.getJob().getId());r.put("status",a.getStatus().name());r.put("match_percentage",a.getMatchPercentage());r.put("applied_at",a.getAppliedAt());r.put("title",a.getJob().getTitle());r.put("company",a.getJob().getCompany().getName());r.put("location",a.getJob().getLocation());return r;}).toList();}
 public Map<String,Object> jobDto(Job j,int match,List<String> reasons){Map<String,Object> r=new LinkedHashMap<>();r.put("id",j.getId());r.put("title",j.getTitle());r.put("company",j.getCompany().getName());r.put("company_name",j.getCompany().getName());r.put("description",j.getDescription());r.put("category",j.getCategory());r.put("employment_type",j.getEmploymentType());r.put("location",j.getLocation());r.put("workplace_type",j.getWorkplaceType());r.put("status",j.getStatus().name());r.put("expires_at",j.getExpiresAt());r.put("application_mode",j.getApplicationMode());r.put("external_apply_url",j.getExternalApplyUrl());r.put("matchPercentage",match);r.put("match_percentage",match);r.put("matchReasons",reasons);return r;}
}
