USE careerforge;
ALTER TABLE community_posts
  ADD COLUMN IF NOT EXISTS topic_tags VARCHAR(500) NULL AFTER media_url,
  ADD COLUMN IF NOT EXISTS spam_score INT NOT NULL DEFAULT 0 AFTER status,
  ADD COLUMN IF NOT EXISTS fraud_score INT NOT NULL DEFAULT 0 AFTER spam_score,
  ADD COLUMN IF NOT EXISTS risk_score INT NOT NULL DEFAULT 0 AFTER fraud_score,
  ADD COLUMN IF NOT EXISTS risk_label VARCHAR(30) NOT NULL DEFAULT 'safe' AFTER risk_score,
  ADD COLUMN IF NOT EXISTS risk_reasons TEXT NULL AFTER risk_label,
  ADD COLUMN IF NOT EXISTS share_count INT NOT NULL DEFAULT 0 AFTER risk_reasons;
CREATE TABLE IF NOT EXISTS post_shares (post_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (post_id, user_id), CONSTRAINT fk_post_shares_post FOREIGN KEY (post_id) REFERENCES community_posts(id) ON DELETE CASCADE, CONSTRAINT fk_post_shares_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS content_reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, post_id BIGINT UNSIGNED NOT NULL, reporter_id BIGINT UNSIGNED NOT NULL, reason VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'open', reviewer_id BIGINT UNSIGNED NULL, reviewed_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_open_report UNIQUE (post_id, reporter_id, status), CONSTRAINT fk_report_post FOREIGN KEY (post_id) REFERENCES community_posts(id) ON DELETE CASCADE, CONSTRAINT fk_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_report_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
