export const jobs = [
  {
    id: 1,
    title: "Product Analyst",
    company: "Pathao",
    location: "Dhaka · Hybrid",
    type: "Full-time",
    match: 94,
    salary: "৳55k–75k",
    logo: "P",
    tone: "bg-coral",
    skills: ["SQL", "Product thinking", "Analytics"],
    posted: "2d ago",
    description: "Turn customer and product data into clear decisions for one of Bangladesh’s fastest-moving digital platforms.",
    review: 4.7,
  },
  {
    id: 2,
    title: "Junior Frontend Engineer",
    company: "Brain Station 23",
    location: "Dhaka · On-site",
    type: "Full-time",
    match: 89,
    salary: "৳45k–65k",
    logo: "B",
    tone: "bg-cobalt",
    skills: ["React", "JavaScript", "CSS"],
    posted: "1d ago",
    description: "Build polished, accessible web products with an experienced cross-functional engineering team.",
    review: 4.5,
  },
  {
    id: 3,
    title: "Data Science Intern",
    company: "bKash",
    location: "Dhaka · Hybrid",
    type: "Internship",
    match: 86,
    salary: "৳25k–35k",
    logo: "b",
    tone: "bg-plum",
    skills: ["Python", "Statistics", "ML"],
    posted: "4d ago",
    description: "Support customer intelligence initiatives with predictive analysis and thoughtful experimentation.",
    review: 4.8,
  },
  {
    id: 4,
    title: "UX Research Associate",
    company: "ShopUp",
    location: "Remote",
    type: "Contract",
    match: 81,
    salary: "৳40k–58k",
    logo: "S",
    tone: "bg-jade",
    skills: ["Research", "Figma", "Interviews"],
    posted: "6d ago",
    description: "Find the human insight behind product opportunities for millions of small businesses.",
    review: 4.3,
  },
];

export const events = [
  { id: 1, day: "04", month: "AUG", title: "Designing your first 90-day career plan", time: "7:00 PM", type: "Workshop", host: "CareerForge", registered: false },
  { id: 2, day: "09", month: "AUG", title: "Dhaka Graduate Career Fair 2026", time: "10:00 AM", type: "Career fair", host: "NSU Auditorium", registered: true },
  { id: 3, day: "13", month: "AUG", title: "Live resume teardown with recruiters", time: "8:30 PM", type: "Live session", host: "Talent Circle", registered: false },
  { id: 4, day: "22", month: "AUG", title: "From campus project to portfolio case study", time: "6:00 PM", type: "Masterclass", host: "BRAC Career Hub", registered: false },
];

export const resources = [
  { id: 1, title: "SQL for Product Decisions", category: "Data & Analytics", level: "Intermediate", time: "2h 40m", progress: 68, tone: "bg-cobalt", icon: "SQL" },
  { id: 2, title: "Write an ATS-ready Resume", category: "Career Toolkit", level: "Beginner", time: "55m", progress: 20, tone: "bg-coral", icon: "CV" },
  { id: 3, title: "Interview Stories that Stick", category: "Communication", level: "Intermediate", time: "1h 20m", progress: 0, tone: "bg-jade", icon: "STAR" },
  { id: 4, title: "Product Analytics Field Guide", category: "Playbook · PDF", level: "Advanced", time: "42 pages", progress: 0, tone: "bg-plum", icon: "PDF" },
  { id: 5, title: "React Patterns for Real Teams", category: "Development", level: "Intermediate", time: "3h 10m", progress: 42, tone: "bg-ink", icon: "JS" },
  { id: 6, title: "Negotiating Your First Offer", category: "Career Toolkit", level: "Beginner", time: "35m", progress: 0, tone: "bg-[#A57945]", icon: "৳" },
];

export const assessments = [
  { id: 1, title: "JavaScript Foundations", category: "Development", questions: 20, minutes: 18, level: "Intermediate", score: 82, color: "cobalt" },
  { id: 2, title: "Data Analysis Essentials", category: "Analytics", questions: 18, minutes: 15, level: "Intermediate", score: null, color: "jade" },
  { id: 3, title: "Professional Communication", category: "Soft Skills", questions: 15, minutes: 12, level: "Beginner", score: 91, color: "coral" },
  { id: 4, title: "Product Thinking", category: "Business", questions: 22, minutes: 20, level: "Advanced", score: null, color: "plum" },
  { id: 5, title: "SQL & Databases", category: "Analytics", questions: 20, minutes: 18, level: "Intermediate", score: 76, color: "ink" },
  { id: 6, title: "UX Research Basics", category: "Design", questions: 16, minutes: 14, level: "Beginner", score: null, color: "sand" },
];

export const communityPosts = [
  {
    id: 1,
    author: "Samiha Noor",
    role: "CSE · BRAC University",
    time: "18 min",
    initials: "SN",
    tone: "bg-coral",
    text: "Just finished my first technical interview! The STAR story worksheet in Career Vault made the behavioral round feel so much more structured. Sharing my biggest takeaway: write the story before you need it.",
    tags: ["Interview prep", "Small wins"],
    likes: 48,
    comments: 9,
    liked: false,
  },
  {
    id: 2,
    author: "Raihan Kabir",
    role: "Data Science · AIUB",
    time: "1 hr",
    initials: "RK",
    tone: "bg-cobalt",
    text: "Does anyone want to form a 4-person SQL assessment study circle for this weekend? Thinking one timed practice session and then a review of the tricky queries.",
    tags: ["Study circle", "SQL"],
    likes: 31,
    comments: 14,
    liked: true,
  },
  {
    id: 3,
    author: "Tasnia Islam",
    role: "BBA · North South University",
    time: "3 hr",
    initials: "TI",
    tone: "bg-jade",
    text: "I moved my readiness score from 61% to 79% in six weeks. Focusing on one role instead of applying everywhere changed everything. Keep showing up—small progress compounds.",
    tags: ["Milestone", "Motivation"],
    likes: 86,
    comments: 21,
    liked: false,
  },
];

export const achievements = [
  { title: "Profile Pioneer", description: "Completed every profile section", icon: "user", unlocked: true, date: "Jul 24" },
  { title: "Skill Sprint", description: "Completed 3 assessments in a week", icon: "zap", unlocked: true, date: "Jul 18" },
  { title: "Community Voice", description: "Received 25 likes on your posts", icon: "message", unlocked: true, date: "Jul 10" },
  { title: "Interview Ready", description: "Reach an 80% readiness score", icon: "target", unlocked: false, progress: 96 },
  { title: "Application Ace", description: "Submit 10 tailored applications", icon: "briefcase", unlocked: false, progress: 70 },
  { title: "Learning Streak", description: "Learn for 7 days in a row", icon: "book", unlocked: false, progress: 57 },
];

export const performanceSeries = [
  { label: "W1", value: 54 },
  { label: "W2", value: 61 },
  { label: "W3", value: 59 },
  { label: "W4", value: 68 },
  { label: "W5", value: 72 },
  { label: "W6", value: 78 },
  { label: "W7", value: 82 },
];
